package az.atlacademy.aHappyFamilyMiniProject.enums;

public enum Species {
    FISH, DOMESTICCAT, DOG, ROBOCAT, PANTHER, HYENA, GORILLA, MONKEY, CHIMPANZEE, KANGAROO, CROCODILE, WOLF, ALLIGATOR, PYTHON, UNKNOWN
}
